steps:
  palworld-server-build-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: hentioe/steamcmd
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      build_args: ENTRYPOINT=entrypoints/palworld-server.sh
      platforms: linux/amd64
      tags: palworld-server
    when:
      branch: master
      event: push
