version: "3"

services:
  palworld-server:
    image: reg.hentioe.dev/steamcmd/steamcmd:palworld-server
    ports:
      - "8211:8211/udp"
    volumes:
      - ./steamapps:/home/steamcmd/steamapps
    restart: always
